MDEXP-265 Applying mapping profile  - holdings and item transformatio…
folio-org/mod-data-export pull request #211
Opened 2020-11-16 13:52 UTC by illia-borysenko

Will provide details later

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2020-11-18 11:59 UTC, illia-borysenko commented on src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
> +      LOGGER.info("Export has been successfully passed");
seems some incorrect changes applied after resolving conflicts, I will check all similar places

2020-11-18 15:52 UTC, andrii-novytskyi approved these changes

2020-11-18 16:10 UTC, Igor-Gorchakov commented on src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
> +          .getById(DEFAULT_MAPPING_PROFILE_ID, params.getTenantId())
No need to store DEFAULT_MAPPING_PROFILE_ID in the ExportManager, just create a method in mappingProfileService to retrieve default profile

2020-11-18 16:11 UTC, Igor-Gorchakov commented on src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
> +          .onFailure(
I don't like this manner of code formatting, let's revert it back to the usual version, and discuss, it with all the backend people

2020-11-18 16:14 UTC, Igor-Gorchakov commented on src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
> +          .onFailure(
This makes the async code completely unreadable for me

2020-11-18 16:21 UTC, Igor-Gorchakov requested changes

2020-11-18 16:21 UTC, Igor-Gorchakov commented on src/main/java/org/folio/service/manager/export/ExportManagerImpl.java
> +  private static final String DEFAULT_MAPPING_PROFILE_ID = "25d81cbe-9686-11ea-bb37-0242ac130002";
No need to store DEFAULT_MAPPING_PROFILE_ID in the ExportManager, just create a method `getDefaultProfile` in the MappingProfileService to retrieve the default profile, store DEFAULT_MAPPING_PROFILE_ID there

2020-11-19 15:31 UTC, Igor-Gorchakov approved these changes

2020-11-19 16:10 UTC, merged

2020-11-19 16:32 UTC, andrii-novytskyi commented on src/main/java/org/folio/service/mapping/RuleFactory.java
> +        LOGGER.error(String.format("No transformation provided for field name: %s, and with record type: %s",
Please, a part from logger, save ErrorLog here